import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Script } from "next/font/google";
import "./globals.css";

const leagueScript = League_Script({
  variable: "--font-league-script",
  subsets: ["latin"],
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${leagueScript.variable}`}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
